version: '3.1'

services:
  
  mta-db:
    image: microsoft/mssql-server-windows-express
    ports:
      - "1433:1433"
    environment: 
      - ACCEPT_EULA=Y
    env_file:
      - db-credentials.env
    networks:
      - app-net

  message-queue:
    image: nats:nanoserver
    ports:
      - "4222:4222"
    networks:
      - app-net

  mta-app:
    image: sixeyed/dddsw7-web:v2
    ports:
      - "80:80"
    env_file:
      - db-credentials.env
    depends_on:
      - mta-db
      - message-queue
    networks:
      - app-net

  mta-save-handler:
    image: sixeyed/dddsw7-save-handler
    env_file:
      - db-credentials.env
    depends_on:
      - mta-db
      - message-queue
    networks:
      - app-net

networks:
  app-net:
    external:
      name: nat