version: '3.1'

services:
  
  db:
    image: microsoft/mssql-server-windows-express
    ports:
      - "1433:1433"
    environment: 
      - ACCEPT_EULA=Y
    env_file:
      - db-credentials.env
    networks:
      - app-net

  web:
    image: frenchben/signup-web
    ports:
      - "80:80"
    env_file:
      - db-credentials.env
    depends_on:
      - db
      - message-queue
    networks:
      - app-net

  message-queue:
    image: nats:nanoserver # NATS is an open-source, high-performance, cloud native messaging system.
    ports:
      - "4222:4222"
    networks:
      - app-net

  signup-save-handler:
    image: frenchben/signup-save-handler
    env_file:
      - db-credentials.env
    depends_on:
      - db
      - message-queue
    networks:
      - app-net

networks:
  app-net:
    external:
      name: nat