version: '3.1'

services:
  
  mta-db:
    image: microsoft/mssql-server-windows-express
    ports:
      - "1433:1433"
    environment: 
      - ACCEPT_EULA=Y
    env_file:
      - db-credentials.env
    networks:
      - app-net

  message-queue:
    image: nats:nanoserver
    ports:
      - "4222:4222"
    networks:
      - app-net

# not on Win10 - needs to be run with --memory which compose doesn't support
#  elasticsearch:
#    image: sixeyed/elasticsearch:nanoserver
#    ports:
#      - "9200:9200"
#    networks:
#      - app-net

  kibana:
    image: sixeyed/kibana:nanoserver
    ports:
      - "5601:5601"
#    depends_on:
#      - elasticsearch
    networks:
      - app-net

  homepage:
    image: sixeyed/dddsw7-homepage
    ports:
      - "8090:80"
    networks:
      - app-net

  mta-app:
    image: sixeyed/dddsw7-web:v2
    ports:
      - "80:80"
    environment:
      - HOMEPAGE_URL=http://homepage
    env_file:
      - db-credentials.env
    depends_on:
      - mta-db
      - message-queue
    networks:
      - app-net

  mta-save-handler:
    image: sixeyed/dddsw7-save-handler
    env_file:
      - db-credentials.env
    depends_on:
      - mta-db
      - message-queue
    networks:
      - app-net

  mta-index-handler:
    image: sixeyed/dddsw7-index-handler
    depends_on:
      - elasticsearch
      - message-queue
    networks:
      - app-net

networks:
  app-net:
    external:
      name: nat